name = "Season 6 1.20"
author = "Maple Modworks"
version = "62dc077"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "259148398f9ccf78ab14cd485bf1898b5e50b1e186833e89c172a7f0fc0cf20d"

[versions]
forge = "47.3.33"
minecraft = "1.20.1"
