name = "Season 6 1.20"
author = "Maple Modworks"
version = "9e203be"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad0cf09b87f068ba5fa4b94f456c66651a44bb63889337170381dfbb880ff32b"

[versions]
forge = "47.3.33"
minecraft = "1.20.1"
