name = "Season 6 1.20"
author = "Maple Modworks"
version = "599cd5d"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "48fe4e422c81302b748c749cb6d957b76eb80520570c44af2af061fd3b24c2ef"

[versions]
forge = "47.3.33"
minecraft = "1.20.1"
