name = "Season 6 1.20"
author = "Maple Modworks"
version = "6d65415"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "725f2bab099e58425fabbb05659c486d09f9d9ca82b30f3196a639d24fff0891"

[versions]
forge = "47.3.33"
minecraft = "1.20.1"
