name = "Season 6 1.20"
author = "Maple Modworks"
version = "198a8e6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96deae61f582f9aeb2d201e9b1c9c1d4a59f0e8028bd0148d14c5633150fd240"

[versions]
forge = "47.3.33"
minecraft = "1.20.1"
