name = "Create-Ive Cogs Season 6"
author = "Canada_LaVearn and Herr Katze"
version = "0.0.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c115caefce6f423314099e1662e0c51b49421ea8145118db4f8ce6de019f539"

[versions]
forge = "43.3.7"
minecraft = "1.19.2"
