name = "Season 6 1.20"
author = "Maple Modworks"
version = "198a8e6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1cd3a0ee7548856013b933ac97fa7926ce78c029229944f3ac33b6e06735a1a3"

[versions]
forge = "47.3.33"
minecraft = "1.20.1"
