name = "Season 6 1.20"
author = "Maple Modworks"
version = "6c1b234"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04b4df4e9aa00ebdb57d645fd983d9a38c3fc32db94ae8f551afebb52e20780a"

[versions]
forge = "47.3.33"
minecraft = "1.20.1"
