name = "Season 6 1.20"
author = "Maple Modworks"
version = "98675cc"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6b1bc17909c9c0ad337db38cb600acec17ab83b8cd9d27c83dae01a91d82117"

[versions]
forge = "47.3.33"
minecraft = "1.20.1"
