name = "Season 6 1.20"
author = "Maple Modworks"
version = "a00fa92"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bec61d7bea656f5449cb23894790bf5e0631bcb04115c98cf09cfa22fde4e052"

[versions]
forge = "47.3.33"
minecraft = "1.20.1"
