name = "Season 6 1.20"
author = "Maple Modworks"
version = "6d65415"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b0f11d9925b8c3b04f6363ec11eb27d9aa0f45f7fe864ea6887361a9c1dd2d0d"

[versions]
forge = "47.3.33"
minecraft = "1.20.1"
