name = "Season 6 1.20"
author = "Maple Modworks"
version = "c2aba78"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1cfcd4df75bfaf2d73ac7b555dfd04cdd5b91d3a4084f1da93effd22b703bb96"

[versions]
forge = "47.3.33"
minecraft = "1.20.1"
