name = "Season 6 1.20"
author = "Maple Modworks"
version = "11361e9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6415b55e7de9f1bfd540c7f4c4d28d15549e1c43ec322358886cc5e722e4219d"

[versions]
forge = "47.3.33"
minecraft = "1.20.1"
