name = "Season 6 1.20"
author = "Maple Modworks"
version = "ec0a923"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e0f58a2a670f3dd2da13c6c9506d522f769dd8728af3a2c3f55abf9db793b27"

[versions]
forge = "47.3.33"
minecraft = "1.20.1"
