name = "Season 6 1.20"
author = "Maple Modworks"
version = "a6f77b4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a14f91b1d4c5d76b14d23eeb26b2eb137771bb1fd7f752cbbef5babcb5d490f"

[versions]
forge = "47.3.33"
minecraft = "1.20.1"
