name = "Season 6 1.20"
author = "Maple Modworks"
version = "779fb71"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ff686dff200832b00cf339975be798985e73821b9359aa95dffc047ab662843"

[versions]
forge = "47.3.33"
minecraft = "1.20.1"
