name = "Season 6 1.20"
author = "Maple Modworks"
version = "6d65415"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "186a8a529014e4bdc20992786163604151e4fa9490100a81234dd03ab24e4b2b"

[versions]
forge = "47.3.33"
minecraft = "1.20.1"
