name = "Season 6 1.20"
author = "Maple Modworks"
version = "cc29b9e"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "94f9ac6cb1716d73b38e4049e4dff2d8d73b16a9508784bb2ecd494266d5731e"

[versions]
forge = "47.3.33"
minecraft = "1.20.1"
