name = "Season 6 1.20"
author = "Maple Modworks"
version = "010065f"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89d20dc836565ef2c9aee262ea098de6fba92d8f831ba86c813e63e3e5c99e23"

[versions]
forge = "47.3.33"
minecraft = "1.20.1"
